language: java

before_install:
  - sudo wget https://github.com/ocaml/opam/releases/download/2.0.0/opam-2.0.0-x86_64-linux -O /usr/bin/opam
  - sudo chmod 755 /usr/bin/opam
  - opam init -a
  - opam update

script: mvn clean package -DskipTests -P solvers
