/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class kodkod_engine_satlab_ParaFrost */

#ifndef _Included_kodkod_engine_satlab_ParaFrost
#define _Included_kodkod_engine_satlab_ParaFrost
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     kodkod_engine_satlab_ParaFrost
 * Method:    make
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_kodkod_engine_satlab_ParaFrost_make
  (JNIEnv *, jclass);

/*
 * Class:     kodkod_engine_satlab_ParaFrost
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_kodkod_engine_satlab_ParaFrost_free
  (JNIEnv *, jobject, jlong);

/*
 * Class:     kodkod_engine_satlab_ParaFrost
 * Method:    addVariables
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_kodkod_engine_satlab_ParaFrost_addVariables
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     kodkod_engine_satlab_ParaFrost
 * Method:    addClause
 * Signature: (J[I)Z
 */
JNIEXPORT jboolean JNICALL Java_kodkod_engine_satlab_ParaFrost_addClause
  (JNIEnv *, jobject, jlong, jintArray);

/*
 * Class:     kodkod_engine_satlab_ParaFrost
 * Method:    solve
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_kodkod_engine_satlab_ParaFrost_solve
  (JNIEnv *, jobject, jlong);

/*
 * Class:     kodkod_engine_satlab_ParaFrost
 * Method:    valueOf
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_kodkod_engine_satlab_ParaFrost_valueOf
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
